services:
  database:
    image: postgres:alpine
    container_name: finman-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - database:/var/lib/postgresql/data

  backend:
    build: .
    image: finman-backend:latest
    container_name: finman-backend
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
    volumes:
      - ./config/${GOOGLE_JSON_KEY_PATH}:/app/config/${GOOGLE_JSON_KEY_PATH}:ro
      - ./.env:/app/.env:ro
    ports:
      - 8080:8080
    depends_on:
      - database

volumes:
  database:
    name: finman-postgres
